// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTJt3RIm6VFkR4pLcQUL4eO1VbEkrVcHY',
    appId: '1:1047128712830:android:18f181c4525993945f9a2f',
    messagingSenderId: '1047128712830',
    projectId: 'clauseverify-app',
    storageBucket: 'clauseverify-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5p6MsirtQDoKHhc-uOPK_HFXgZhUc_LQ',
    appId: '1:1047128712830:ios:1cd0da007decaae75f9a2f',
    messagingSenderId: '1047128712830',
    projectId: 'clauseverify-app',
    storageBucket: 'clauseverify-app.firebasestorage.app',
    iosClientId: '1047128712830-0chpauimk032t684pee8u2n8j8bbfd7v.apps.googleusercontent.com',
    iosBundleId: 'com.clauseverify.app',
  );
}
